### ISSUE TITLE
constructor taking string is not compliant with locals

### ISSUE THREAD

**Issue by ghost** [dlang-community/d-money#4]
e.g when using the thousand separator plus the decimal separator there are bad surprises:

```d
EUR y = EUR("1.000.000,00");
writeln(y);          // not one million !
```

**Comment by mw66** [comment]
which country you are in?

It only parse "1,000,000.00"?  i.e dot as decimal separator.

**Comment by qznc** [comment]
The proposal is to use locals to determine how we parse a string instead of the currently hardcoded "1,000,000.00" format only.

I see the downside that using the locale internally is a subtle influence which is easy to overlook. Such dependencies should be introduced in the application and not in libraries like d-money.

As a compromise, d-money could provide a function which takes a string and a locale to encapsulate the parsing. The application would still be responsible to pick the locale from the environment, from the client, or wherever.
